### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by kidd** [yhvh/erc-yt#1]
Hello,
Nice package there. I'm the author of erc-youtube (https://github.com/kidd/erc-youtube.el ). I see that most of the functionality is common between both. 

What about joining efforts into just one package? I can easily give you commit rights

**Comment by yhvh** [comment]
Sounds good. I'm busy ATM with final year uni stuff, give me a month or so.
I'll set a reminder.

**Comment by kidd** [comment]
yup. np :). Good luck with your finals!
